import { createFileRoute } from "@tanstack/react-router";
import midtransClient from "midtrans-client";

// Initialize the Snap client once outside the handler
const snap = new midtransClient.Snap({
  isProduction: false, 
  serverKey: process.env.MIDTRANS_SERVER_KEY || "",
  clientKey: process.env.MIDTRANS_CLIENT_KEY || "", 
});

async function handler(request: Request) {
  try {
    const body = await request.json();
    
    // 1. Destructure `cartSummary` from the body alongside `orderNotes`
    const { orderId, grossAmount, customerDetails, itemDetails, orderNotes, cartSummary } = body;

    const parameter = {
      transaction_details: {
        order_id: orderId,
        gross_amount: grossAmount, 
      },
      item_details: itemDetails, 
      customer_details: customerDetails, 
      
      // 2. Put the customer's notes in field 1 (if they exist)
      custom_field1: orderNotes ? orderNotes.substring(0, 255) : undefined,
      
      // 3. Pass the cartSummary generated by the frontend into field 2
      custom_field2: cartSummary ? cartSummary.substring(0, 255) : undefined,       
    };

    const transaction = await snap.createTransaction(parameter);

    return new Response(JSON.stringify({ token: transaction.token }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}

export const Route = createFileRoute("/api/midtrans")({
  server: {
    handlers: {
      POST: ({ request }) => handler(request),
    },
  },
});