/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CooperationRouteImport } from './routes/cooperation'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as PaymentErrorRouteImport } from './routes/payment-error'
import { Route as PaymentinfoRouteImport } from './routes/paymentinfo'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SizeRouteImport } from './routes/size'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ApiCooperationRouteImport } from './routes/api/cooperation'
import { Route as ApiMidtransRouteImport } from './routes/api/midtrans'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperationRoute = CooperationRouteImport.update({
  id: '/cooperation',
  path: '/cooperation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentErrorRoute = PaymentErrorRouteImport.update({
  id: '/payment-error',
  path: '/payment-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentinfoRoute = PaymentinfoRouteImport.update({
  id: '/paymentinfo',
  path: '/paymentinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeRoute = SizeRouteImport.update({
  id: '/size',
  path: '/size',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCooperationRoute = ApiCooperationRouteImport.update({
  id: '/api/cooperation',
  path: '/api/cooperation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMidtransRoute = ApiMidtransRouteImport.update({
  id: '/api/midtrans',
  path: '/api/midtrans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cooperation': typeof CooperationRoute
  '/delivery': typeof DeliveryRoute
  '/payment-error': typeof PaymentErrorRoute
  '/paymentinfo': typeof PaymentinfoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size': typeof SizeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thankyou': typeof ThankyouRoute
  '/videos': typeof VideosRoute
  '/api/cooperation': typeof ApiCooperationRoute
  '/api/midtrans': typeof ApiMidtransRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cooperation': typeof CooperationRoute
  '/delivery': typeof DeliveryRoute
  '/payment-error': typeof PaymentErrorRoute
  '/paymentinfo': typeof PaymentinfoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size': typeof SizeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thankyou': typeof ThankyouRoute
  '/videos': typeof VideosRoute
  '/api/cooperation': typeof ApiCooperationRoute
  '/api/midtrans': typeof ApiMidtransRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cooperation': typeof CooperationRoute
  '/delivery': typeof DeliveryRoute
  '/payment-error': typeof PaymentErrorRoute
  '/paymentinfo': typeof PaymentinfoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size': typeof SizeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thankyou': typeof ThankyouRoute
  '/videos': typeof VideosRoute
  '/api/cooperation': typeof ApiCooperationRoute
  '/api/midtrans': typeof ApiMidtransRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cooperation'
    | '/delivery'
    | '/payment-error'
    | '/paymentinfo'
    | '/privacy-policy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/size'
    | '/terms-of-service'
    | '/thankyou'
    | '/videos'
    | '/api/cooperation'
    | '/api/midtrans'
    | '/api/uploadthing'
    | '/api/webhook'
    | '/collections/$slug'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cooperation'
    | '/delivery'
    | '/payment-error'
    | '/paymentinfo'
    | '/privacy-policy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/size'
    | '/terms-of-service'
    | '/thankyou'
    | '/videos'
    | '/api/cooperation'
    | '/api/midtrans'
    | '/api/uploadthing'
    | '/api/webhook'
    | '/collections/$slug'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/cooperation'
    | '/delivery'
    | '/payment-error'
    | '/paymentinfo'
    | '/privacy-policy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/size'
    | '/terms-of-service'
    | '/thankyou'
    | '/videos'
    | '/api/cooperation'
    | '/api/midtrans'
    | '/api/uploadthing'
    | '/api/webhook'
    | '/collections/$slug'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CooperationRoute: typeof CooperationRoute
  DeliveryRoute: typeof DeliveryRoute
  PaymentErrorRoute: typeof PaymentErrorRoute
  PaymentinfoRoute: typeof PaymentinfoRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SizeRoute: typeof SizeRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ThankyouRoute: typeof ThankyouRoute
  VideosRoute: typeof VideosRoute
  ApiCooperationRoute: typeof ApiCooperationRoute
  ApiMidtransRoute: typeof ApiMidtransRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperation': {
      id: '/cooperation'
      path: '/cooperation'
      fullPath: '/cooperation'
      preLoaderRoute: typeof CooperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-error': {
      id: '/payment-error'
      path: '/payment-error'
      fullPath: '/payment-error'
      preLoaderRoute: typeof PaymentErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paymentinfo': {
      id: '/paymentinfo'
      path: '/paymentinfo'
      fullPath: '/paymentinfo'
      preLoaderRoute: typeof PaymentinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size': {
      id: '/size'
      path: '/size'
      fullPath: '/size'
      preLoaderRoute: typeof SizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cooperation': {
      id: '/api/cooperation'
      path: '/api/cooperation'
      fullPath: '/api/cooperation'
      preLoaderRoute: typeof ApiCooperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/midtrans': {
      id: '/api/midtrans'
      path: '/api/midtrans'
      fullPath: '/api/midtrans'
      preLoaderRoute: typeof ApiMidtransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CooperationRoute: CooperationRoute,
  DeliveryRoute: DeliveryRoute,
  PaymentErrorRoute: PaymentErrorRoute,
  PaymentinfoRoute: PaymentinfoRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SizeRoute: SizeRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ThankyouRoute: ThankyouRoute,
  VideosRoute: VideosRoute,
  ApiCooperationRoute: ApiCooperationRoute,
  ApiMidtransRoute: ApiMidtransRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
