/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CooperationRouteImport } from './routes/cooperation'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as PaymentinfoRouteImport } from './routes/paymentinfo'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SizeRouteImport } from './routes/size'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ApiMidtransRouteImport } from './routes/api/midtrans'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AdminItemsIdRouteImport } from './routes/admin.items.$id'
import { Route as AdminItemsNewRouteImport } from './routes/admin.items.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperationRoute = CooperationRouteImport.update({
  id: '/cooperation',
  path: '/cooperation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentinfoRoute = PaymentinfoRouteImport.update({
  id: '/paymentinfo',
  path: '/paymentinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeRoute = SizeRouteImport.update({
  id: '/size',
  path: '/size',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ApiMidtransRoute = ApiMidtransRouteImport.update({
  id: '/api/midtrans',
  path: '/api/midtrans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsIdRoute = AdminItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsNewRoute = AdminItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/cooperation': typeof CooperationRoute
  '/delivery': typeof DeliveryRoute
  '/paymentinfo': typeof PaymentinfoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/size': typeof SizeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/videos': typeof VideosRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/api/midtrans': typeof ApiMidtransRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/admin/items/$id': typeof AdminItemsIdRoute
  '/admin/items/new': typeof AdminItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cooperation': typeof CooperationRoute
  '/delivery': typeof DeliveryRoute
  '/paymentinfo': typeof PaymentinfoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/size': typeof SizeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/videos': typeof VideosRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/api/midtrans': typeof ApiMidtransRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/admin/items/$id': typeof AdminItemsIdRoute
  '/admin/items/new': typeof AdminItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/cooperation': typeof CooperationRoute
  '/delivery': typeof DeliveryRoute
  '/paymentinfo': typeof PaymentinfoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/size': typeof SizeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/videos': typeof VideosRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/api/midtrans': typeof ApiMidtransRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/admin/items/$id': typeof AdminItemsIdRoute
  '/admin/items/new': typeof AdminItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/cooperation'
    | '/delivery'
    | '/paymentinfo'
    | '/privacy-policy'
    | '/refund-policy'
    | '/size'
    | '/terms-of-service'
    | '/videos'
    | '/admin/catalog'
    | '/admin/categories'
    | '/api/midtrans'
    | '/api/uploadthing'
    | '/api/webhook'
    | '/collections/$slug'
    | '/admin/'
    | '/collections/'
    | '/admin/items/$id'
    | '/admin/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cooperation'
    | '/delivery'
    | '/paymentinfo'
    | '/privacy-policy'
    | '/refund-policy'
    | '/size'
    | '/terms-of-service'
    | '/videos'
    | '/admin/catalog'
    | '/admin/categories'
    | '/api/midtrans'
    | '/api/uploadthing'
    | '/api/webhook'
    | '/collections/$slug'
    | '/admin'
    | '/collections'
    | '/admin/items/$id'
    | '/admin/items/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/cooperation'
    | '/delivery'
    | '/paymentinfo'
    | '/privacy-policy'
    | '/refund-policy'
    | '/size'
    | '/terms-of-service'
    | '/videos'
    | '/admin/catalog'
    | '/admin/categories'
    | '/api/midtrans'
    | '/api/uploadthing'
    | '/api/webhook'
    | '/collections/$slug'
    | '/admin/'
    | '/collections/'
    | '/admin/items/$id'
    | '/admin/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CooperationRoute: typeof CooperationRoute
  DeliveryRoute: typeof DeliveryRoute
  PaymentinfoRoute: typeof PaymentinfoRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SizeRoute: typeof SizeRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  VideosRoute: typeof VideosRoute
  ApiMidtransRoute: typeof ApiMidtransRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperation': {
      id: '/cooperation'
      path: '/cooperation'
      fullPath: '/cooperation'
      preLoaderRoute: typeof CooperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paymentinfo': {
      id: '/paymentinfo'
      path: '/paymentinfo'
      fullPath: '/paymentinfo'
      preLoaderRoute: typeof PaymentinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size': {
      id: '/size'
      path: '/size'
      fullPath: '/size'
      preLoaderRoute: typeof SizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/midtrans': {
      id: '/api/midtrans'
      path: '/api/midtrans'
      fullPath: '/api/midtrans'
      preLoaderRoute: typeof ApiMidtransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items/$id': {
      id: '/admin/items/$id'
      path: '/items/$id'
      fullPath: '/admin/items/$id'
      preLoaderRoute: typeof AdminItemsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items/new': {
      id: '/admin/items/new'
      path: '/items/new'
      fullPath: '/admin/items/new'
      preLoaderRoute: typeof AdminItemsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminItemsIdRoute: typeof AdminItemsIdRoute
  AdminItemsNewRoute: typeof AdminItemsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminItemsIdRoute: AdminItemsIdRoute,
  AdminItemsNewRoute: AdminItemsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CooperationRoute: CooperationRoute,
  DeliveryRoute: DeliveryRoute,
  PaymentinfoRoute: PaymentinfoRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SizeRoute: SizeRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  VideosRoute: VideosRoute,
  ApiMidtransRoute: ApiMidtransRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
